### ISSUE TITLE
500 error when pulling roster

### ISSUE THREAD

**Issue by iccowan** [VATUSA/api#35]
https://api.vatusa.net/v2/facility/ztl/roster?apikey=[API_Key]

{"status":"error","msg":"Trying to get property 'id' of non-object","exception":"ErrorException"}

Returned with a 500 error.

**Comment by iccowan** [comment]
Change: this only occurs when using the sandbox API key. It does not appear to work anymore.

**Comment by bnahin** [comment]
Fixed in #36. API Sandbox/Testing is a work in progress, so using this key currently has **no effect** (changes are still persisted to the database).
