### ISSUE TITLE
Laravel Upgrade

### ISSUE THREAD

**Issue by bnahin** [VATUSA/api#57]
Update Laravel to 8.x

**Comment by dhawton** [comment]
After discussions, decided to upgrade to Laravel 6.x (LTS) with a goal of upgrading to 9.x (next LTS) at the end of CY.

Reasons:
- 8.x is not LTS, it has the same EOL as 6.x and security patches are applied to 6.x as well
- 9.x is the next LTS expected to release in Sept
- l5-Swagger does not support OpenAPI 2.0 specs beginning in the version needed for 8.x, this will give time to rewrite the documentation to OpenAPI 3.0 specification without rush while returning to be inside the maintenance window

**Comment by dhawton** [comment]
Before merging, any env variables that define cache time will need to be edited. Beginning with 5.8, times for Cache are in seconds rather than minutes. Code has been reflected to manipulate this, but areas where pulled from environment variables will need to be updated before rolling out this PR.
